### ISSUE TITLE
Albums with just a number for a name crash soularr.py, ie album is called '7'

### ISSUE THREAD

**Issue by yroyathon** [mrusse/soularr#15]
Searching album: 7
Traceback (most recent call last):
  File "/app/soularr.py", line 423, in <module>
    failed = grab_most_wanted(wanted)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 226, in grab_most_wanted
    success = search_and_download(grab_list, querry, all_tracks, all_tracks[0], artist_name, release)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 150, in search_and_download
    search = slskd.searches.search_text(searchText = querry,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slskd_api/apis/searches.py", line 69, in search_text
    response = self.session.post(url, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slskd_api/client.py", line 60, in <lambda>
    session.hooks = {'response': lambda r, *args, **kwargs: r.raise_for_status()}
                                                            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://host.docker.internal:5030/soulseek/api/v0/searches
 Fatal error! Exiting...

**Comment by AdamWHY2K** [comment]
try setting `album_prepend_artist` to `True` in the config file, i had a similar issue and that fixed it.

**Comment by yroyathon** [comment]
@AdamWHY2K I don't see that anywhere in the config.  Is that supposed to be under [Release Settings] section?

**Comment by yroyathon** [comment]
Ah I see it in the python code, under [Search Settings] section.  I'll give it a try.

**Comment by mrusse** [comment]
Duplicate of [https://github.com/mrusse/soularr/issues/8](https://github.com/mrusse/soularr/issues/8) closing for now. Please update on original issue. Thanks.

**Comment by yroyathon** [comment]
I made that change in config.ini under section [Search Settings] (album_prepend_artist = True), but the error/failure still happened for me.

Searching album: 7
Traceback (most recent call last):
  File "/app/soularr.py", line 423, in <module>
    failed = grab_most_wanted(wanted)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 226, in grab_most_wanted
    success = search_and_download(grab_list, querry, all_tracks, all_tracks[0], artist_name, release)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 150, in search_and_download
    search = slskd.searches.search_text(searchText = querry,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slskd_api/apis/searches.py", line 69, in search_text
    response = self.session.post(url, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slskd_api/client.py", line 60, in <lambda>
    session.hooks = {'response': lambda r, *args, **kwargs: r.raise_for_status()}
                                                            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://host.docker.internal:5030/soulseek/api/v0/searches

**Comment by mrusse** [comment]
Make sure you have the most recent version. "Searching album: 7" indicates that the artist name isn't actually being appended to the album title. The feature was only recently added to the main branch so you will have to update your docker image if you haven't already

**Comment by yroyathon** [comment]
That has done the trick, I finally got past the '7' album, thanks.
