### ISSUE TITLE
Soularr crashes if a download is cancelled

### ISSUE THREAD

**Issue by davemacrae** [mrusse/soularr#32]
If , during the download process, a download is cancelled and removed within SLSKD, Soularr will crash when it attempts to process the download.

```
Username: <redacted> Directory: @@<redacted>
-------------------
Waiting for downloads... monitor at: http://192.168.1.13:5030/downloads
Traceback (most recent call last):
  File "/home/dave/src/soularr/./soularr.py", line 521, in <module>
    failed = grab_most_wanted(wanted_records)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/src/soularr/./soularr.py", line 308, in grab_most_wanted
    downloads = slskd.transfers.get_downloads(username)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.local/lib/python3.12/site-packages/slskd_api/apis/transfers.py", line 112, in get_downloads
    response = self.session.get(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/.local/lib/python3.12/site-packages/slskd_api/client.py", line 60, in <lambda>
    session.hooks = {'response': lambda r, *args, **kwargs: r.raise_for_status()}
                                                            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.1.13:5030/api/v0/transfers/downloads/<redacted>
```

**Comment by mrusse** [comment]
Soularr will already handle this you just have to wait to see the message signifying the download has failed. It only checks for these failed downloads after all the downloads have been added. So if you remove it before then it will cause a crash. Will add some error handling but just dont remove the downloads after you cancel and it will be fine.

**Comment by davemacrae** [comment]
Thanks. Figured that one out after watching a few more fails. Edge case error handling is always a massive pain.
