### ISSUE TITLE
Not a bug, I just can't make this work

### ISSUE THREAD

**Issue by janaxhell** [mrusse/soularr#57]
Before coming here I had a 2 hours chat with chatGPT that led to no solution. 
I have a lidarr-on-steroids working fine. I also have a nicotine+ working, but AFAIK it is mandatory to deploy slskd to make this work, so I stopped nicotine+ and deployed slskd. I have set all the keys and paths in composes and configs, but there is clearly something wrong.
slskd UI is accessible, but Disconnected (from there I edited its config). soularr starts, but spits this error:

```
[INFO|soularr|L349] 2024-12-25T14:57:12+0000: Searching album: Absolute Beginners
[ERROR|soularr|L690] 2024-12-25T14:57:12+0000: Traceback (most recent call last):
  File "/app/soularr.py", line 688, in <module>
    failed = grab_most_wanted(wanted_records)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 350, in grab_most_wanted
    success = search_and_download(grab_list, query, all_tracks, all_tracks[0], artist_name, release)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/soularr.py", line 243, in search_and_download
    search = slskd.searches.search_text(searchText = query,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slskd_api/apis/searches.py", line 69, in search_text
    response = self.session.post(url, json=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slskd_api/client.py", line 60, in <lambda>
    session.hooks = {'response': lambda r, *args, **kwargs: r.raise_for_status()}
                                                            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://192.168.1.94:5030/api/v0/searches
[ERROR|soularr|L691] 2024-12-25T14:57:12+0000: 
 Fatal error! Exiting...
25/12/2024 14:57:12 - Waiting for 300 seconds before checking again...
```

Meanwhile slskd, although accessible, says this:

```
                   ????         ????       ????
           ??????? ?  ? ??????? ?  ???? ????  ?
           ?__ --? ?  ? ?__ --? ?    ?? ?  -  ?
           ??????? ???? ??????? ??????? ???????
??????????????????????????????????????????????????????????
?           GNU AFFERO GENERAL PUBLIC LICENSE            ?
?                   https://slskd.org                    ?
?                                                        ?
?              0.22.1.0 (0.22.1.0+ac451814)              ?
??????????????????????????????????????????????????????????
[14:50:19 INF] Version: 0.22.1.0 (0.22.1.0+ac451814)
[14:50:19 INF] System: .NET 8.0.11, Unix 6.1.0.0, 64 bit, 4 processors
[14:50:19 INF] Process ID: 8 (64 bit)
[14:50:19 INF] Invocation ID: 8b4ef305-048b-4658-b7b4-20165594bc86
[14:50:19 INF] Instance Name: default
[14:50:19 INF] Configuring application...
[14:50:19 INF] Using application directory /app
[14:50:19 INF] Using configuration file /app/slskd.yml
[14:50:19 INF] Storing application data in /app/data
[14:50:19 WRN] Authentication of web requests is DISABLED
[14:50:20 INF] Listening for HTTP requests at http://0.0.0.0:5030/
[14:50:20 INF] Listening for HTTPS requests at https://0.0.0.0:5031/
[14:50:20 INF] Using randomly generated self-signed certificate
[14:50:21 INF] Using base url /
[14:50:21 INF] Serving static content from /slskd/wwwroot
[14:50:21 INF] Configuration complete.  Starting application...
[14:50:21 INF] Blacklist disabled
[14:50:21 INF] Application started
[14:50:22 INF] Listening for incoming connections on 0.0.0.0:50300
[14:50:22 INF] Checking GitHub Releases for latest version
[14:50:22 INF] Initializing shares
[14:50:22 INF] Share cache StorageMode is 'Memory'. Attempting to load from backup...
[14:50:22 INF] Share cache backup validated. Attempting to restore...
[14:50:22 INF] Version 0.22.1.0 is up to date.
[14:50:23 INF] Share cache successfully restored from backup
[14:50:23 INF] Share cache loaded from disk successfully. Sharing 38401 directories and 557563 files
[14:51:17 INF] Warming browse response cache...
[14:51:18 ERR] Error caching browse response: Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Soulseek.Messaging.MessageBuilderExtensions.WriteFile(MessageBuilder builder, File file)
   at Soulseek.Messaging.MessageBuilderExtensions.WriteDirectory(MessageBuilder builder, Directory directory)
   at Soulseek.Messaging.Messages.BrowseResponseFactory.ToByteArray(BrowseResponse browseResponse)
   at Soulseek.BrowseResponse.ToByteArray()
   at slskd.Application.CacheBrowseResponse()
[14:51:18 INF] Starting system clock...
[14:51:18 INF] System clock started
[14:51:18 WRN] Not connecting to the Soulseek server; username and/or password invalid.  Specify valid credentials and manually connect, or update config and restart.
```
This is soularr config.ini

```
[Lidarr]
api_key = =====================
host_url = http://192.168.1.94:8686
#This should be the path mounted in lidarr that points to your slskd download directory.
#If Lidarr is not running in Docker then this may just be the same dir as Slskd is using below.
download_dir = /soulseek

[Slskd]
#Api key from Slskd. Need to set this up manually. See link to Slskd docs above.
api_key = ==========================================
host_url = http://192.168.1.94:5030
#Slskd download directory. Should have set it up when installing Slskd.
download_dir = /app/downloads
#Removes searches from Slskd after the search finishes.
delete_searches = False
#Maximum time (in seconds) that the script will wait for downloads to complete.
#This is used to prevent the script from running forever due to a stalled download. Defaults to 1 hour.
stalled_timeout = 3600

[Release Settings]
#Selects the release with the most common amount of tracks out of all the releases.
use_most_common_tracknum = True
allow_multi_disc = True
#See full list of countries below.
accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada,Japan
#See full list of formats below.
accepted_formats = CD,Digital Media

[Search Settings]
search_timeout = 5000
maximum_peer_queue = 50
#Min upload speed in bit/s
minimum_peer_upload_speed = 0
#Replace "flac,mp3" with "flac" if you just want flacs.
allowed_filetypes = flac,mp3
ignored_users = User1,User2,Fred,Bob
#Set to False if you only want to search for complete albums
search_for_tracks = False
#Set to True if you want to add the artist's name to the beginning of the search for albums
album_prepend_artist = False
track_prepend_artist = True
#Valid search types: all || incrementing_page || first_page
  #"all" will search for every wanted record everytime soularr is run.
  #"incrementing_page" will start with the first page and increment to the next on each run.
  #"first_page" will repeatedly search the first page.
#If using the search type "first_page" remove_wanted_on_failure should be enabled.
search_type = incrementing_page
#How mancy records to grab each run, must be a number between 1 - 2,147,483,647
number_of_albums_to_grab = 10
#Unmonitors the album if Soularr can't find it and places it in "failure_list.txt". 
#Failed albums can be re monitored by filtering "Unmonitored" in the Lidarr wanted list.
remove_wanted_on_failure = False
#Comma separated list of words that can't be in the title of albums or tracks. Case insensitive.
title_blacklist = BlacklistWord1,blacklistword2

[Logging]
#These options are passed into the logger's basicConfig() method as-is.
#This means, if you're familiar with Python's logging module, you can configure
#the logger with options beyond what's listed here by default.
#For more information on available options  --  https://docs.python.org/3/library/logging.html#logging.basicConfig
level = INFO
# Format of log message  --  https://docs.python.org/3/library/logging.html#logrecord-attributes
format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
# Format of datetimes  --  https://docs.python.org/3/library/time.html#time.strftime
datefmt = %Y-%m-%dT%H:%M:%S%z
```

This is slskd config

```
debug: false
remoteConfiguration: true
remoteFileManagement: false
instanceName: default
flags:
  noLogo: false
  noStart: false
  noConfigWatch: false
  noConnect: false
  noShareScan: false
  forceShareScan: false
  noVersionCheck: false
  logSQL: false
  experimental: false
  volatile: false
  caseSensitiveRegEx: false
  legacyWindowsTcpKeepalive: false
relay:
  enabled: false
  mode: controller
  controller:
    address: null
    ignoreCertificateErrors: false
    apiKey: null
    secret: null
    downloads: false
  agents: {}
permissions:
  file:
    mode: null
directories:
  incomplete: /app/incomplete
  downloads: /app/downloads
shares:
  directories:
    - /music
  filters: []
  cache:
    storageMode: memory
    workers: 4
    retention: null
global:
  upload:
    slots: 10
    speedLimit: 2147483647
  limits:
    queued:
      files: null
      megabytes: null
      failures: null
    daily:
      files: null
      megabytes: null
      failures: null
    weekly:
      files: null
      megabytes: null
      failures: null
  download:
    slots: 2147483647
    speedLimit: 2147483647
groups:
  default:
    upload:
      priority: 1
      strategy: roundrobin
      slots: 2147483647
      speedLimit: 2147483647
    limits:
      queued:
        files: null
        megabytes: null
        failures: null
      daily:
        files: null
        megabytes: null
        failures: null
      weekly:
        files: null
        megabytes: null
        failures: null
  leechers:
    thresholds:
      files: 1
      directories: 1
    upload:
      priority: 1
      strategy: roundrobin
      slots: 2147483647
      speedLimit: 2147483647
    limits:
      queued:
        files: null
        megabytes: null
        failures: null
      daily:
        files: null
        megabytes: null
        failures: null
      weekly:
        files: null
        megabytes: null
        failures: null
  blacklisted:
    members: []
    cidrs: []
  userDefined: {}
blacklist:
  enabled: false
  file: null
filters:
  search:
    request: []
rooms: []
web:
  port: 5030
  https:
    disabled: false
    port: 5031
    force: false
    certificate:
      pfx: null
      password: null
  urlBase: /
  contentPath: wwwroot
  logging: false
  authentication:
    disabled: true
    username: "*****"
    password: "*****"
    jwt:
      key: "*****"
      ttl: 604800000
    apiKeys:
      myapikey:
        key: "*****"
        role: readwrite
        cidr: 192.168.1.0/24
retention:
  search: null
  transfers:
    upload:
      succeeded: null
      errored: null
      cancelled: null
    download:
      succeeded: null
      errored: null
      cancelled: null
  files:
    complete: null
    incomplete: null
  logs: 180
logger:
  loki: null
  disk: false
  noColor: false
metrics:
  enabled: false
  url: /metrics
  authentication:
    disabled: false
    username: slskd
    password: "*****"
feature:
  swagger: false
soulseek:
  address: 192.168.1.94
  port: 50300
  username: "*****"
  password: "*****"
  description: |
    A slskd user. https://github.com/slskd/slskd
  listenIpAddress: 0.0.0.0
  listenPort: 50300
  diagnosticLevel: Info
  distributedNetwork:
    disabled: false
    disableChildren: false
    childLimit: 25
    logging: false
  connection:
    timeout:
      connect: 10000
      inactivity: 15000
    buffer:
      read: 16384
      write: 16384
      transfer: 262144
      writeQueue: 50
    proxy:
      enabled: false
      address: null
      port: null
      username: null
      password: null
integration:
  webhooks: {}
  scripts: {}
  ftp:
    enabled: false
    address: null
    port: 21
    encryptionMode: auto
    ignoreCertificateErrors: false
    username: null
    password: null
    remotePath: /
    overwriteExisting: true
    connectionTimeout: 5000
    retryAttempts: 3
  pushbullet:
    enabled: false
    accessToken: null
    notificationPrefix: "From slskd:"
    notifyOnPrivateMessage: true
    notifyOnRoomMention: true
    retryAttempts: 3
    cooldownTime: 900000
```

For context, running this on an x86 OMV6 server. 
What am I doing wrong?

**Comment by mrusse** [comment]
Surprised chatgpt didnt pick this up after 2 hours...

`Not connecting to the Soulseek server; username and/or password invalid.  Specify valid credentials and manually connect, or update config and restart`

Please join the discord for further troubleshooting.
