### ISSUE TITLE
Albums with just symbols crash container

### ISSUE THREAD

**Issue by zolfey** [mrusse/soularr#8]
First discovered the issue with Trippie Redd ! and then discovered it with Ed Sheeran +

```soularr  | Selected release for Ed Sheeran: Official, Europe, CD, Mediums: 1
soularr  | Searching album: +
soularr  | Traceback (most recent call last):
soularr  |   File "/app/soularr.py", line 375, in <module>
soularr  |     failed = grab_most_wanted(wanted)
soularr  |              ^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/app/soularr.py", line 220, in grab_most_wanted
soularr  |     success = search_and_download(grab_list, querry, all_tracks, all_tracks[0], artist_name, release)
soularr  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/app/soularr.py", line 146, in search_and_download
soularr  |     search = slskd.searches.search_text(searchText = querry,
soularr  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/usr/local/lib/python3.11/site-packages/slskd_api/apis/searches.py", line 69, in search_text
soularr  |     response = self.session.post(url, json=data)
soularr  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
soularr  |     return self.request("POST", url, data=data, json=json, **kwargs)
soularr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
soularr  |     resp = self.send(prep, **send_kwargs)
soularr  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 710, in send
soularr  |     r = dispatch_hook("response", hooks, r, **kwargs)
soularr  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/usr/local/lib/python3.11/site-packages/requests/hooks.py", line 30, in dispatch_hook
soularr  |     _hook_data = hook(hook_data, **kwargs)
soularr  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/usr/local/lib/python3.11/site-packages/slskd_api/client.py", line 60, in <lambda>
soularr  |     session.hooks = {'response': lambda r, *args, **kwargs: r.raise_for_status()}
soularr  |                                                             ^^^^^^^^^^^^^^^^^^^^
soularr  |   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
soularr  |     raise HTTPError(http_error_msg, response=self)
soularr  | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.254.41:5030/api/v0/searches
soularr  | 
soularr  | 
soularr  |  Fatal error! Exiting...```

**Comment by mrusse** [comment]
Thanks for the feedback. Will look into it.

**Comment by zolfey** [comment]
> Thanks for the feedback. Will look into it.

The PR that is open fixes it but I moved to the Dockerized version, thank you so much for making this.
